[phases.setup]
nixPkgs = ["go", "gcc", "sqlite"]

[phases.install]
cmds = ["go mod download"]

[phases.build]
cmds = ["CGO_ENABLED=1 go build -o bin/server ./cmd/server"]

[start]
cmd = "./bin/server"
